# Generated by Django 5.1.3 on 2024-11-13 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_centro', models.CharField(max_length=100)),
                ('codigo_centro', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('Admin', 'Administrador'), ('Centro', 'Responsable de Centro')], max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDeEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=100)),
                ('codigo_plan', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_acreditacion', models.DateField(blank=True, null=True)),
                ('fecha_proxima_acreditacion', models.DateField(blank=True, null=True)),
                ('centro_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_acreditaciones.centro')),
            ],
        ),
        migrations.CreateModel(
            name='Acreditacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completada', 'Completada'), ('Rechazada', 'Rechazada')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('plan_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_acreditaciones.plandeestudio')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_modificada', models.CharField(max_length=50)),
                ('tipo_cambio', models.CharField(choices=[('Creación', 'Creación'), ('Modificación', 'Modificación'), ('Eliminación', 'Eliminación')], max_length=50)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('detalles_cambio', models.TextField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_acreditaciones.usuario')),
            ],
        ),
    ]
